### PR TITLE
Support for Centos 7.2

### PR DESCRIPTION
**Pull request by acranox**
7.2 added a space in the timezone output like this: "Time zone:"
judicous use of awk can perform a case insensitive search for the line with timezone or time zone, and split the line at the colon to retrieve the timezone

### CODE REVIEW

**Comment by pietervogelaar** [comment]
Please merge this

**Comment by scopenco** [comment]
+1

**Comment by pc-mreeves** [comment]
Looks like this is fixed in current master:
https://github.com/dragonsmith/timezone_lwrp/blob/master/providers/default.rb#L74

`cmd_check_if_set += " | /usr/bin/awk '/Time.*zone/{print}'"`

**Comment by acranox** [comment]
It would have been nice if someone made a note in this PR that it's been fixed.

**Pull request closed without merging**
